spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-0919ddacc34e484fbe8050411ad722f4
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        distance-type: COSINE_DISTANCE
#        dimensions: 1536
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    url: jdbc:postgresql://pgm-bp1216n0nwzus24two.rwlb.rds.aliyuncs.com/ai-agent
    username: hzh
    password: Dn293830


server:
  port: 8123
  servlet:
    context-path: /api
# 接口文档配置 springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hezhaohui.aiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn